### ISSUE TITLE
Instructions on how to run this on ubuntu / deploy

### ISSUE THREAD

**Issue by kittyandrew** [vladgr/idb#1]
Please, could you elaborate on instructions how to run this on ubuntu. And how to deploy it as a service. Do I just need to build this somehow and put behind webserver as a reverse proxy?

I have no experience running flutter apps.

**Comment by vladgr** [comment]
To use Flutter app on Ubuntu build Flutter for Linux and you will get Linux Desktop app. I didn't tested it on Linux.
Or run as Web version that will work in Chrome browser.

To deploy as Web PWA. 
Compile as Web. 

```
flutter build web --release --web-renderer canvaskit
```

It just static web site that you can host anywhere.
If you host on VPS, all you need Nginx and Lets encrypt certificate.

You can even host on AWS S3 bucket. I never did this, but you will find lot of tutorials.
I am talking about Flutter app.

Besides you will need backend written on some language that you know.

Optionally you can use Firebase or Supabase instead of backend.
In that case you will need to change Flutter code, just fork repo and do whatever you want!

**Comment by kittyandrew** [comment]
Okay. If I will ever get to do this (before anyone else does; and if you do, ping me), I will open source it.
